name: RoShader

on:
  push:
    branches:
      - main  # Trigger build when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # or windows-latest if you're using Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MinGW (or Clang or GCC)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake clang

      - name: Build with CMake
        run: |
          cmake .
          cmake --build .
